FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV HELMVERSION="3.3.4"

RUN microdnf install -y curl tar gzip gettext && \
    microdnf clean all

COPY bin/entrypoint/* bin/helm/* bin/prerequisites/* /usr/local/bin/
RUN ["bash", "-c", "/usr/local/bin/helm-install.sh"]

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
